version: '3.7'

services:
  dynamo:
    image: dwmkerr/dynamodb
    ports:
      - 8000:8000
  dev:
    depends_on:
      - dynamo
    build:
      context: .
      target: dev
    volumes:
      - .:/app:cached
    environment:
      - SBT_OPTS=-Xms512M -Xmx2G -Xss2M -XX:MaxMetaspaceSize=1024M -XX:+CMSClassUnloadingEnabled
      - DYNAMO_ENDPOINT=http://dynamo:8000
    command: >
      bash -c "./init_bloop.sh && bash"

  sonar:
    depends_on:
      - dynamo
    build:
      context: .
      target: sonar
    volumes:
      - .:/app
    environment:
      - SBT_OPTS=-Xms512M -Xmx2G -Xss2M -XX:MaxMetaspaceSize=1024M -XX:+CMSClassUnloadingEnabled
      - DYNAMO_ENDPOINT=http://dynamo:8000
      - SONAR_CLOUD_TOKEN

  release:
    build:
      context: .
      target: release
    volumes:
      - ~/.ssh:/root/.ssh
      - .:/app
    environment:
      - SBT_OPTS=-Xms512M -Xmx2G -Xss2M -XX:MaxMetaspaceSize=1024M -XX:+CMSClassUnloadingEnabled
      - GITHUB_TOKEN
